import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Providers from "@/components/Providers";
import { Toaster } from "react-hot-toast";
import { ThemeProviders } from "@/components/ui/ThemeProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ContextualAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      {/* We wrap the Providers around the client so that react-query can cache any data from previously-called end-points. */}
      <Providers>
        <html lang="en">
          <body className={inter.className}>
            <ThemeProviders>
              {children}
              {/* Toaster creates the alerts */}
              <Toaster />
            </ThemeProviders>
          </body>
        </html>
      </Providers>
    </ClerkProvider>
  );
}
